name: jbm # Or your actual app name
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- CORE DEPENDENCIES ---
  # Use the latest versions from pub.dev
  objectbox: ^4.0.0
  objectbox_flutter_libs: any 
  flutter_riverpod: ^2.5.1
  path_provider: ^2.1.3
  intl: ^0.20.2
  fl_chart: ^1.1.1
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  google_sign_in: ^7.2.0
  googleapis: ^15.0.0
  path: ^1.9.1

  http: any
dev_dependencies:
  analyzer: ^8.2.0
  flutter_test:
    sdk: flutter
  
  # --- CORE DEV DEPENDENCIES ---
  build_runner: ^2.4.9
  objectbox_generator: ^4.0.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true