import 'package:isar/isar.dart';

part 'account.g.dart'; // This will be generated by build_runner

@collection
class Account {
  Id id = Isar.autoIncrement; // You can also use id = null to auto increment

  @Index(type: IndexType.value, unique: true)
  late String name; // e.g., "M-PESA", "CRDB", "Cash"

  late double balance;

  Account();
}
